### ISSUE TITLE
Hamburger Menu / Mobile Media Query

### ISSUE THREAD

**Issue by claytical** [gabycostales/firefighterApp#10]
When you go to the site on a mobile device or shrink your browser window down, the side menu doesn't go away/show the hamburger menu.

**Comment by gabycostales** [comment]
This has been added and needs more styling work but let me know if all the needed functionality is there as we want it

**Comment by lbtran** [comment]
@gabycostales good start thx. Here are some updates:

1. mobile header should be sticky (also reduce height so it takes up less vertical space)
2. when not logged in, hide Login/Register links
3. when logged in, put user menu items into the hamburger: so Dashboard through About (as you have it) then add below that Account Settings and Log Out with the same font awesome icons used in standard browser.

**Comment by gabycostales** [comment]
Made all these updates - let me know what you guys think
