### ISSUE TITLE
Styling for h2 and h4 headings in PER

### ISSUE THREAD

**Issue by lbtran** [gabycostales/firefighterApp#11]
We've designed the print version of the PER, and the headings and subheadings should be styled as such to make the hierarchy more clear (as we've done with the print version). These styles are also part of the style guide (see relevant screenshot there).

For example on PER > Rehabilitation > Provide Initial Rehabilitation Vitals:

You can remove the hr tags and style the h2 and h4 elements to the following for standard browser. Will need to adjust values for mobile.

h2 {
    background-color: black;
    color: white;
    padding: 10px;
    border-radius: 3px;
}

h4 {
    font-size: 18px;
    background-color: #ccc;
    padding: 10px;
    margin-bottom: 20px;
    font-weight: bold;
    border-radius: 2px;
}

**Comment by gabycostales** [comment]
Should I also have these apply for the Profile create/update pages?
