### ISSUE TITLE
Creating a Report / Hazard Materials Error

### ISSUE THREAD

**Issue by claytical** [gabycostales/firefighterApp#15]
Trying to add a hazardous material and clicking save and continue I get this error:
 
Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`forge`.`hazardousmaterialreport_hazardousmaterialtype`, CONSTRAINT `hazardousmaterialreport_hazardousmaterialtype_hmt_id_foreign` FOREIGN KEY (`hmt_id`) REFERENCES `hazardous_material_types` ) (SQL: insert into `hazardousmaterialreport_hazardousmaterialtype` (`h_id`, `hmt_id`) values (3, 4))

**Comment by gabycostales** [comment]
Fixed
