### ISSUE TITLE
If you create a report and don't select Incident Type and click Save and Continue or click off, it throws error 

### ISSUE THREAD

**Issue by lbtran** [gabycostales/firefighterApp#16]
If you select Incident Type and then try and change it, it gives an appropriate pop up error. However, if you're creating a new PER and click to switch to another section or click Save and Continue, it throws an error. It should instead remind the user that I.Type is required.

**Comment by gabycostales** [comment]
Now if they try to select another step before saving a type it will redirect them back to step 1 with an error saying they have to select a type and hit save before moving on

**Comment by claytical** [comment]
OK. just to double check for everyone before closing this out, the steps to reproduce the error message:

1. Click Create PER
2. Click on PPE or Rehablitation
3. Get heinous error message

**Comment by gabycostales** [comment]
Correct! - The error shows up as a red message under incident type

**Comment by gabycostales** [comment]
Wait totally just realized what you meant by this - this is basically the same as issue #32 then. So the solution I wrote last night solves this.
