### ISSUE TITLE
If you create a fire report, and select an extinguishment value, you get an error

### ISSUE THREAD

**Issue by claytical** [gabycostales/firefighterApp#17]
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`forge`.`extinguishmentmean_firereport`, CONSTRAINT `extinguishmentmean_firereport_em_id_foreign` FOREIGN KEY (`em_id`) REFERENCES `extinguishment_means` (`id`) ON DELETE CASCADE) (SQL: insert into `extinguishmentmean_firereport` (`em_id`, `fire_report_id`) values (4, 5))

**Comment by gabycostales** [comment]
Fixed
