### ISSUE TITLE
Creating a fire report, step 4, protective gear error

### ISSUE THREAD

**Issue by claytical** [gabycostales/firefighterApp#18]
If you select a personal protective equipment, you get the following error on save:

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`forge`.`fireppetype_firereport`, CONSTRAINT `fireppetype_firereport_fpt_id_foreign` FOREIGN KEY (`fpt_id`) REFERENCES `fire_ppe_types` (`id`) ON DELETE CASCADE) (SQL: insert into `fireppetype_firereport` (`fire_report_id`, `fpt_id`) values (5, 6))

**Comment by gabycostales** [comment]
Fixed
