### ISSUE TITLE
Creating a fire report, step 5 (decontamination)

### ISSUE THREAD

**Issue by claytical** [gabycostales/firefighterApp#19]
If you check one of the decontamination checkboxes, you get this error:

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`forge`.`deconscenereplaced_firereport`, CONSTRAINT `deconscenereplaced_firereport_dsr_id_foreign` FOREIGN KEY (`dsr_id`) REFERENCES `decon_scene_replaced` (`id`) ON DELETE CASCADE) (SQL: insert into `deconscenereplaced_firereport` (`dsr_id`, `fire_report_id`) values (5, 5))

**Comment by gabycostales** [comment]
fixed
