### ISSUE TITLE
For View Profile and Create PER submenu: these should be numbered (instead of circle bullet)

### ISSUE THREAD

**Issue by lbtran** [gabycostales/firefighterApp#2]

**Comment by gabycostales** [comment]
Steps now numbered - let me know if it looks ok

**Comment by lbtran** [comment]
looks great! Can we number View Full Profile as #6 (I get that it's different but it's like a final step and makes it look more consistent). @gabycostales thank you!

**Comment by gabycostales** [comment]
Cool, done! (will reflect on live site next time I deploy)
