### ISSUE TITLE
Mobile - (1) View PERs and (2) Most Recent PERs section on Dashboard

### ISSUE THREAD

**Issue by lbtran** [gabycostales/firefighterApp#23]
Reduce displayed columns on mobile to these, in this order:

1) PER #
2) Date Last Updated (formatted to save space as MM/DD/YY 00:20)
3) Action button (this is great Gaby, thanks for adding it)

**Comment by lbtran** [comment]
@gabycostales please check the styling of the Actions modal so that the options list appears near (or at least closer) to where the user clicked. Currently in mobile the list appears below the widget (so if they user doesn't look or scroll down, it seems like clicking/tapping did nothing).

**Comment by gabycostales** [comment]
Action dropdown should now be in the correct place
