### ISSUE TITLE
Clicking Create PER takes you to current PER if it's still in progress (doesn't create new)

### ISSUE THREAD

**Issue by lbtran** [gabycostales/firefighterApp#24]
When you click "Create PER", it takes you to most recent in-progress PER (with the current values displayed). If the last PER you were working on is still In Progress, there should be a confirmation message when you click on Create PER: "Would you like to continue updating your last PER or would you like to create a new PER now?" (basically we need a way for a user to create a new PER without finishing their last one).

Also, ideally once they click on Save & Continue on "Incident Information" (with an Incident Type selected) it should generate a PER # that displays to the user. This can appear in front of (on same line as) where we just added Incident Type. For example, "PER #005, Incident Type: Fire"

Note: If the last PER a user created was Submitted, then clicking "Create PER" should take you to a blank form and it looks like it works this way currently.

**Comment by gabycostales** [comment]
If Create PER clicked - modal prompt pops up if they were working on a report. In progress report is already persisted so they just start a new report.

And correct - if last report was submitted then clicking Create PER just takes you to a new blank report form.

**Comment by gabycostales** [comment]
Displays PER # next to the incident type
