### ISSUE TITLE
View PER > Date Last Updated (appears as current time and as GMT)

### ISSUE THREAD

**Issue by lbtran** [gabycostales/firefighterApp#28]
System clock looks like it is set to GMT, please update to EST. Screenshot was taken at May 11 9:48am EST but appears as 1:48pm. 

Also, it looks like Date Last Updated is the current date/time - it keeps being updated to current GMT time when I refresh the page (all are the same time except 1 which is stuck at noon).

![screen shot 2016-05-11 at 9 48 52 am](https://cloud.githubusercontent.com/assets/3252270/15183098/9d76547c-175d-11e6-864d-abf14735b8fc.png)

![screen shot 2016-05-11 at 9 51 34 am](https://cloud.githubusercontent.com/assets/3252270/15183176/015b4ac4-175e-11e6-8c54-ad91c90b9359.png)

**Comment by claytical** [comment]
If this can't be fixed, change the column to use Date Created for the time being.

**Comment by gabycostales** [comment]
Fixed to use EST and reflects when time last updated at. Working now on making sure if you update a child model of the base report (basically anything after step 1) it touches/update the base report "updated_at" time column

**Comment by gabycostales** [comment]
Just deployed an update and this is now working as it should
