### ISSUE TITLE
Profile -> Employment Info -> Do You Have Another Job?

### ISSUE THREAD

**Issue by claytical** [gabycostales/firefighterApp#29]
Change the secondary field from a dropdown (When was the last time you worked at that job?) to a textfield (numeric, 2 digits) that reads:

How many days in a month do you work in another job?

**Comment by claytical** [comment]
Typo in the fix, it reads "in anothe job"

**Comment by gabycostales** [comment]
This is now live - Numeric, accepted max value is 31. Also fixed the typo
