### ISSUE TITLE
Scrolling Side Menu on Mobile

### ISSUE THREAD

**Issue by claytical** [gabycostales/firefighterApp#31]
On certain devices (or just a tiny window height) you can't scroll down to see the rest of the side menu. About link can't be accessed.

If this is fixed, the tests can be run on desktops.

**Comment by gabycostales** [comment]
This scrolls if sidebar goes beyond the initial height I set, but working now on making it scoll if window is less than that min-height

**Comment by gabycostales** [comment]
(note that the height it has to exceed to scroll is 300 px)
