### ISSUE TITLE
Accessing PPE section after clicking on Create Report throws an error

### ISSUE THREAD

**Issue by claytical** [gabycostales/firefighterApp#32]
This happened on Barbara's PC but I can't reproduce it.

Click Create Report, then click on the PPE link.

<img width="1015" alt="55095e69-dc1c-42ff-a93f-d398da4c0104" src="https://cloud.githubusercontent.com/assets/2013067/15194410/c2c27854-1790-11e6-82c8-20e17d6eed3d.png">

**Comment by gabycostales** [comment]
Solution for #35 also solves this problem - check added for null report before trying to access its ppeTypes
