### ISSUE TITLE
View PER Mobile, Viewable Fields

### ISSUE THREAD

**Issue by claytical** [gabycostales/firefighterApp#34]
Right now, PER # and Date Last Updated are visible. The incident number, incident type, date & time, and status should be visible.

Perhaps we can put all of the fields into one column so that it collapses correctly for mobile? ie:

Incident Number: 1021
Incident Type: Fire
Date and Time: 2/2/2016 1:15pm

in one column...

**Comment by gabycostales** [comment]
Done in View PERs - but let's just add PER # and Date Last Updated to this column? actions out of view initially otherwise

**Comment by claytical** [comment]
Ok, I didn't see this in the push from an hour ago.

Sent from my iPhone

On May 12, 2016, at 9:48 AM, Gaby Costales <notifications@github.com<mailto:notifications@github.com>> wrote:


Done in View PERs - but let's just add PER # and Date Last Updated to this column? actions out of view initially otherwise

-

**Comment by gabycostales** [comment]
Just deployed it a little while ago

**Comment by claytical** [comment]
ok looks good!
