### ISSUE TITLE
Profile > Step 3: Add another Rx and hit Enter, takes you to Step 4 (rather than adding that Rx)

### ISSUE THREAD

**Issue by lbtran** [gabycostales/firefighterApp#4]

**Comment by gabycostales** [comment]
So I think this issue may be the design not properly reflecting whats going on - to add a new Rx the user just has to hit add another and type in the name in the new input field. All the filled out Rx input fields get saved to the db when you submit. Should I append the given Rx to a list of some sort instead when "add another" is hit to reflect that better?

**Comment by lbtran** [comment]
It's a usability issue. 

What you can do is write JS to say, when cursor is in that text field (and any that has Add Another capability), to interpret Enter as same thing as clicking Add Another.

**Comment by gabycostales** [comment]
This is now implemented for adding another Rx and name of a fighter (Hazardous Material step 2).
