### ISSUE TITLE
Shift Cycle A,B,C, Other Logic

### ISSUE THREAD

**Issue by claytical** [gabycostales/firefighterApp#40]
When the agency selected is PBCFR and the user selects Shift Cycle 24/48, then the shift field should be a dropdown that allows you to select A, B, C or Unassigned. 

If you select Unassigned, then the shift field textbox is shown.

At all other times, the way it is now is how it should be.

**Comment by gabycostales** [comment]
Done - I anticipated some confusion though since Station Number and Shift Cycle also have "Unassigned" and "Other", so it may not be clear that they need to enter an other value if they pick "Unassigned" for Shift. So I gave Shift both "Unassigned" and "Other" options for consistency.
