### ISSUE TITLE
New Report Populated with Another Report's Data

### ISSUE THREAD

**Issue by claytical** [gabycostales/firefighterApp#41]
This is happening on another person's computer, I can't replicate. If there are cookies being stored, that might be the case:

-Create an account with no reports.
-Create new report.
-Get prompted about creating a new one or continuing what's in progress.
-See report from another account populated in the in progress report (that shouldn't exist)

**Comment by gabycostales** [comment]
Now when a user logs out the session is cleared and session cleared when browser is closed. (Note this essentially the same as issue #53 so I'll close this one)
