### ISSUE TITLE
Race Not Selectable in Create/Update Profile

### ISSUE THREAD

**Issue by claytical** [gabycostales/firefighterApp#43]
At first it worked, but after clicking on other fields, all checkboxes couldn't be unchecked.

**Comment by gabycostales** [comment]
Having trouble recreating this issue - does this still happen?

**Comment by claytical** [comment]
I believe it's when the window is small enough that it's single column but the side nav is still available.
<img width="968" alt="screen shot 2016-05-13 at 10 41 05 am" src="https://cloud.githubusercontent.com/assets/2013067/15251413/4519b7e2-18f7-11e6-8e1e-d5003d79ef0d.png">

**Comment by gabycostales** [comment]
Ah yeah that was it. Fixed - its now working
