### ISSUE TITLE
Crash on submitting a report

### ISSUE THREAD

**Issue by claytical** [gabycostales/firefighterApp#57]
Pressed back on browser and returned to Review & Submit, selected update on section 1, and was redirected to a blank section 1 form

**Comment by gabycostales** [comment]
Only encountering this on the Android default browser

**Comment by gabycostales** [comment]
Added safeguards to make sure the user cannot attempt to submit a report more than once + prevent browser from caching that Review page as biggest safe guard. User's shouldn't be able to reach any of the Create Report / update pages after submitting a report. If you try to go back after submitting it will redirect you back to the home page (and if you hit back again to report/create). It displays the submit confirmation modal again however so we may want to reopen this issue as a bug.
